Data design deep dive overhaul
avohq/docs pull request #1211
Opened 2024-06-18 14:22 UTC by thoragudf

New videos, updated steps according to changes in the produt. Please check if I forgot something!

2024-06-18 14:23 UTC, hugihlynsson commented
#### 📝 Changed routes:


| [**…-tracking-plan/metrics**](https://docs-eg8irrp2p.avo-dev.app/data-design/avo-tracking-plan/metrics) | [**…sign/start-data-design**](https://docs-eg8irrp2p.avo-dev.app/data-design/start-data-design) |
|:-:|:-:|
|<a href="https://docs-eg8irrp2p.avo-dev.app/data-design/avo-tracking-plan/metrics"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/aysow9VvcgJGaLERovsLqJt4ALmuOlc34T_mytFL4_jjnWLCECpbxL516AuacRpg80-3gfcojLSZ8WqJrxsKbw.png&w=600" alt="Screenshot of /data-design/avo-tracking-plan/metrics" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_Yy9Mj1hr7jE_Be5VlzETf2FRRmHJXEdruFTkKyjidgPGhJzhD37LO3YG573KXAvxCRWUUdfLyhWoycgTGhQDw.png">(view full size)</a> |<a href="https://docs-eg8irrp2p.avo-dev.app/data-design/start-data-design"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/iIQrMIuiQjonlV1tpvDSouib0X36GVKbiq7EskoYyEQD3E1Pic2-RE76pPC_fDZCa1eGvGAf0VOye5SbidhOGQ.png&w=600" alt="Screenshot of /data-design/start-data-design" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/WIdasJ56Ja3c7I_gVD5f-Q6Zuso60Q0XC1jup3cB_Tpv26J-smlZtgPWH5AQQAEfmjgjOvh3CDC9PGU6wteInw.png">(view full size)</a> |







Commit 307033c021e9901238ee63b01b09e23865cba6c3 (https://docs-eg8irrp2p.avo-dev.app).

2024-06-18 16:03 UTC, hugihlynsson reviewed
Looking good, the new videos are 🔥🔥🔥

2024-06-18 16:03 UTC, hugihlynsson commented on pages/data-design/start-data-design.mdx
> +Open a new branch by clicking the icon "main" in the left sidebar. Then you are prompted to open an existing branch or creating a new one.
```suggestion
Open a new branch by clicking the icon to the right of "main" in the left sidebar. Then you are prompted to open an existing branch or creating a new one.
```

2024-06-18 16:03 UTC, hugihlynsson commented on pages/data-design/start-data-design.mdx
> +    href={'data-design/define-sources-and-destinations'}
404, probably needs a leading slash:
```suggestion
    href="/data-design/define-sources-and-destinations"
```

2024-06-19 12:21 UTC, thoragudf commented on pages/data-design/avo-tracking-plan/metrics.mdx
> +At Avo, we have developed a framework that we call the **Purpose Meeting** to help us align on goals and metrics. Read more in the blog post about [tracking the right product metrics]() by our CEO, S
eagle eyes

2024-06-19 13:25 UTC, thoragudf commented on pages/data-design/avo-tracking-plan/metrics.mdx
> +    href={'/docs/data-design/guides/documenting-purpose-meetings-in-avo'}
correct!

2024-06-19 14:36 UTC, hugihlynsson approved these changes

2024-06-20 14:18 UTC, 1212spark requested changes
Some of these are stylistic changes and some are typos; good to go after review and accept/reject

2024-06-20 14:18 UTC, 1212spark commented on pages/data-design/start-data-design.mdx
> +- **any** (available upon request): any data type is allowed and not type validation will occur
"not" --> "no"

2024-06-20 14:18 UTC, 1212spark commented on pages/data-design/start-data-design.mdx
> +All properties are required by default and we recommend trying to keep them required in as many cases a possible. That means that the Avo developer tools will throw and error if the property is not a
"cases a possible" --> "cases as possible"

2024-06-20 14:18 UTC, 1212spark commented on pages/data-design/start-data-design.mdx
> +All properties are required by default and we recommend trying to keep them required in as many cases a possible. That means that the Avo developer tools will throw and error if the property is not a
"throw and error" --> "throw an error"

2024-06-20 14:18 UTC, 1212spark commented on pages/data-design/start-data-design.mdx
> +Now you know how to define and maintain your metrics and events in Avo and it's time to learn how to [review branch changes](/workflow/review) and [request implementation](/workflow/request-implement
"Now **that** you know . . . in Avo, it's time"

2024-06-20 15:02 UTC, thoragudf commented on pages/data-design/avo-tracking-plan/metrics.mdx
>  Metrics are used to measure the success of a feature. Usually more than one metrics are necessary to be able to evaluate the success of a feature. Example metrics for a feature that is meant to impro
Changed to: "How do metrics in Avo work?"

2024-06-20 15:06 UTC, thoragudf commented on pages/data-design/start-data-design.mdx
> +- **string**: only all string values are allowed
I think "only string values are allowed" does the trick well enough

2024-06-20 15:41 UTC, 1212spark approved these changes
🚀

2024-06-21 13:42 UTC, merged