Update review doc
avohq/docs pull request #1350
Opened 2024-11-28 14:18 UTC by aleks-tpom6oh

2024-11-28 14:37 UTC, hugihlynsson commented
#### 📝 Changed routes:


| [**/workflow/review**](https://docs-4b2le71gv.avo-dev.app/workflow/review) |
|:-:|
|<a href="https://docs-4b2le71gv.avo-dev.app/workflow/review"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/rP5LKQo6GTqFdcB_21XV9NszJqwiSo5EkBTdwiUFnzyRlGD8yEEUBE72viDvTfYogXU5hVjr0IcN3_TUvnCrCw.png&w=600" alt="Screenshot of /workflow/review" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/rhwdThLbJFcwJPCspYIRSWWMSphwbPJsvY2YvWi6FmZRBQw-Tz2Wt7tfC18EczabXLvRyhtvy6l9CvTfNz9X0w.png">(view full size)</a> |







Commit c82f08d67c14023ad0d95036d4a9e8375eadc259 (https://docs-4b2le71gv.avo-dev.app).

2024-11-28 16:40 UTC, klaraavo commented on pages/workflow/review.mdx
>  ## Submit a review
```suggestion
## Submitting a review
```

2024-11-28 16:40 UTC, klaraavo commented on pages/workflow/review.mdx
> +The branch review screen in Avo summarizes the changes that have been suggested on the branch.
```suggestion
The "view changes" screen in Avo summarizes the changes that have been suggested on the branch.
```

2024-11-28 16:40 UTC, klaraavo commented on pages/workflow/review.mdx
> +From there, you can comment on every item that has been introduced or changed on your branch, ask questions and suggest changes.
```suggestion
###Commenting on changes

From the "view changes screen", you can comment on every item that has been introduced or changed on your branch, ask questions and suggest changes.
```

2024-11-29 09:53 UTC, klaraavo requested changes

2024-11-29 09:53 UTC, klaraavo commented on pages/data-design/branches/approval-workflows.mdx
> +Branch status makes it transparent at which step the peer-review process is and when it is changed, notifications are sent out to all branch collaborators.
```suggestion
Branch status makes it transparent at which step the peer-review process is and when it is changed, notifications are sent out to assigned reviewers and all other branch collaborators.
```

2024-11-29 09:53 UTC, klaraavo commented on pages/data-design/branches/approval-workflows.mdx
> +- **Changes requested**: Indicates that a reviewer has requested changes to the branch before it can be approved.
```suggestion
- **Changes requested**: A reviewer has requested changes to the branch before it can be approved. 
```

2024-11-29 09:53 UTC, klaraavo commented on pages/data-design/branches/index.mdx
> +When you've suggested changes to your tracking, mark the branch as ready for review, and assign someone from your team to review the changes.
```suggestion
When you've suggested changes to your tracking, mark the branch as ready for review, and assign an editor or admin to review the changes.
```

2024-11-29 09:53 UTC, klaraavo commented on pages/data-design/branches/workspace-notifications.mdx
> +  - Changes requested
Didn't see this represented in the build 🤔

2024-11-29 09:53 UTC, klaraavo commented on pages/data-design/branches/workspace-notifications.mdx
> +## Enabling Slack notifications
Also don't see this structural change represented in the build (moving this section to below the first one)

2024-11-29 09:53 UTC, klaraavo commented on pages/workflow/review.mdx
> +title: '2. Review changes'
Need to represent this in the nav as well

2024-11-29 09:53 UTC, klaraavo commented on pages/data-design/branches/workspace-notifications.mdx
> +# Notifications
Need to represent this in the nav as well

2024-11-29 12:09 UTC, klaraavo approved these changes

2024-11-29 12:09 UTC, merged