signatures docs
avohq/docs pull request #457
Opened 2022-05-04 16:32 UTC by bjornj12

Initial Draft for Webhook signature docs. 

Creating these docs before starting to implement, to make sure our customers agree with the approach we take

2022-05-04 16:48 UTC, hugihlynsson commented
It looks like mdx thinks some text is a component, we might have to escape those characters somehow

2022-05-05 09:05 UTC, bragur requested changes
Nice! Couple of fixed needed though

2022-05-05 09:05 UTC, bragur commented on pages/workspace/tracking-plan/webhook-signing.mdx
> +}```
Should this be like this? Don’t know if this matters in the grand scheme of things but it seems to mess up the github preview of it. Sorry, don’t know how to escape the code block out
```suggestion
\```
{
    ts:1651677541,
    v1:30703093db3c532c6f0ab1f1f9eb80b134f5bf6e2ff7064c403aab7582df0667
}
\```
```

2022-05-05 09:05 UTC, bragur commented on pages/workspace/tracking-plan/webhook-signing.mdx
> +Compute an HMAC using the SHA256 has function. Use the webhooks endpoint signing secret from <your publishing page> as the key, and use the `signed_payload` string as the message.
Hmm is that also meant to be a link?
```suggestion
Compute an HMAC using the SHA256 hash function. Use the webhooks endpoint signing secret from _your publishing page_ as the key, and use the `signed_payload` string as the message.
```

2022-05-05 09:05 UTC, bragur commented on pages/workspace/tracking-plan/webhook-signing.mdx
> +1. Extract the timestamp and signature from the header
Do we have h4? (####)

2022-05-05 10:46 UTC, hugihlynsson commented
#### 📝 Changed routes:


| [**…g-plan/webhook-signing**](https://docs-ipakqxcrk.avo-dev.app/workspace/tracking-plan/webhook-signing) |
|:-:|
|<a href="https://docs-ipakqxcrk.avo-dev.app/workspace/tracking-plan/webhook-signing"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/-t4taC_b26fYADFsV7bnHY7jgRSb29cqEC38p5B1SnOj8cmlK_iG158bMUHPW86RvsnMXih1bgzs2l2x2FIlEw.png&w=600" alt="Screenshot of /workspace/tracking-plan/webhook-signing" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/OOHr2gTNBGehVy8KWWAWbXaDET_BA49bNp_vSALBDPObzKjHZ9B_QuDPbQ8s3UoL1dww79HsbS0-kJlNptNVCQ.png">(view full size)</a> |







Commit 4dd98aee0d7aa275bdaf96e6f18f9d0ab0201bd6 (https://docs-ipakqxcrk.avo-dev.app).

2022-05-05 11:09 UTC, hugihlynsson approved these changes

2022-05-05 13:41 UTC, bragur approved these changes

2022-05-05 13:49 UTC, merged